services:
  balancer:
    build:
      context: .
      dockerfile: docker/balancer/balancer.Dockerfile
    depends_on:
      - nginx-backend1
      - nginx-backend2
      - frontend
    ports:
      - "8001:80"
    networks:
      - otus-hw04
    container_name: balancer-hw04

  nginx-backend1:
    build:
      context: .
      dockerfile: docker/nginx/nginx.Dockerfile
    networks:
      - otus-hw04
    volumes:
      - php_fpm_socket1:/var/run/php
    container_name: nginx-backend1-hw04

  nginx-backend2:
    build:
      context: .
      dockerfile: docker/nginx/nginx.Dockerfile
    networks:
      - otus-hw04
    volumes:
      - php_fpm_socket2:/var/run/php
    container_name: nginx-backend2-hw04

  php-fpm1:
    build:
      context: .
      dockerfile: docker/php/php.Dockerfile
    networks:
      - otus-hw04
      - redis-cluster-net
    volumes:
      - php_fpm_socket1:/var/run/php
    container_name: php-fpm1-hw04

  php-fpm2:
    build:
      context: .
      dockerfile: docker/php/php.Dockerfile
    networks:
      - otus-hw04
      - redis-cluster-net
    volumes:
      - php_fpm_socket2:/var/run/php
    container_name: php-fpm2-hw04

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/vue.prod.Dockerfile
    networks:
      - otus-hw04
    container_name: vue-frontend-hw04

networks:
  otus-hw04:
    driver: bridge

  redis-cluster-net:
    external: true

volumes:
  php_fpm_socket1:
  php_fpm_socket2:
