services:
  balancer:
    image: vlavlamat/balancer-hw04:prod
    restart: always

  nginx-backend1:
    image: vlavlamat/nginx-backend-hw04:prod
    restart: always

  nginx-backend2:
    image: vlavlamat/nginx-backend-hw04:prod
    restart: always

  php-fpm1:
    image: vlavlamat/php-fpm-hw04:prod
    environment:
      - APP_ENV=production
    restart: always

  php-fpm2:
    image: vlavlamat/php-fpm-hw04:prod
    environment:
      - APP_ENV=production
    restart: always

  frontend:
    image: vlavlamat/vue-hw04:prod
    restart: always
